### ISSUE TITLE
Split "challenges/models.py" into a separate class per challenge

### ISSUE THREAD

**Issue by nicoknoll** [projectsecure/projectsecure-api#37]
As a user I want to be able to easily create my own challenges and give them to the project secure team. I want to be able to do this without changing existing files.

*Requirements:*
- Split "challenges/models.py" into a separate class per challenge and move them into a custom subfolder
- Refactor challenges/models.py to load all challenges from that folder
- Create skeleton file for challenges to share with external developers

**Comment by nikriek** [comment]
I had it like this before, but removed it to keep it simple for now. We should def. follow that approach with the project's growth. A skeleton/documentation can be found in the readme already

**Comment by nicoknoll** [comment]
@nikriek It's probably smarter if you not only split the models but if you rather create a /challenges/ folder and then a subfolder per challenge including model, serializer, and graphics if needed. What do you think?

**Comment by nikriek** [comment]
Jep, I thought about keeping the Django structure. But it's actually a pretty nice idea!

**Comment by nicoknoll** [comment]
so for the structure I would propose that you always have an "config.py" or "init.py" or so in the folder as well that contains ... well the config (like the static meta info and the challange slug that can be used for the slug and the database table). So we can use something like "glob" to fetch all the challenges and load them.

Ideally the system doesn't have to know anything about the challenge. So we can refactor the challenges in own repos as they all follow the same strucure and work on them seperately (maybe julius can add some better wording :P).

**Comment by nikriek** [comment]
this was already included in some way..

**Comment by nikriek** [comment]
We should also create a generator command

**Comment by nikriek** [comment]
<img width="791" alt="bildschirmfoto 2016-12-25 um 14 13 31" src="https://cloud.githubusercontent.com/assets/2924261/21471271/657985fa-caac-11e6-94ee-6d981372e4b6.png">
