### ISSUE TITLE
Implement user delete endpoint

### ISSUE THREAD

**Issue by nicoknoll** [projectsecure/projectsecure-api#38]
As a user I want to be able to delete my account and all related information.

To consider: soft delete?

**Comment by nikriek** [comment]
This ticket is fairly easy. In a user deletion process all related entries get removed automatically through `on_delete=CASCADE`. @boeckhoff can you take over that ticket? In the end it's only one small endpoint implementation

**Comment by boeckhoff** [comment]
[https://github.com/projectsecure/projectsecure-api/pull/47](url)
