### ISSUE TITLE
Add "color" field to user collection on server

### ISSUE THREAD

**Issue by nicoknoll** [projectsecure/projectsecure-api#7]
As a user I want to be able to choose a color when I signup. This color will be used on several places in the UI (like Twitter is doing it) to customize my experience.

![niklas](https://cloud.githubusercontent.com/assets/1143670/20029484/6fabe35a-a34d-11e6-99d6-0f1c7f0cd0e4.gif)

**Comment by nikriek** [comment]
Let's defer the implementation for this one as other stuff has to be done first :)

**Comment by nikriek** [comment]
https://github.com/projectsecure/projectsecure-api/pull/34
